package Test;

import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Input6 extends javax.swing.JFrame {

    public Input6() {
        initComponents();
        setLocationRelativeTo(null);
    }


    public String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = md.digest(password.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInput1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonsSave = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelNewUsersTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldInput2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldInput3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldInput4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldInput5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldInput6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Sisi                            :");

        jTextFieldInput1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInput1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldInput1.setText("Enter Value...");
        jTextFieldInput1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInput1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInput1FocusLost(evt);
            }
        });
        jTextFieldInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInput1ActionPerformed(evt);
            }
        });

        jButtonsSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonsSave.setText("Save");
        jButtonsSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsSaveActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelNewUsersTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelNewUsersTitle.setText("Input 6");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sisi                            :");

        jTextFieldInput2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInput2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldInput2.setText("Enter Value...");
        jTextFieldInput2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInput2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInput2FocusLost(evt);
            }
        });
        jTextFieldInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInput2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sisi                            :");

        jTextFieldInput3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInput3.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldInput3.setText("Enter Value...");
        jTextFieldInput3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInput3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInput3FocusLost(evt);
            }
        });
        jTextFieldInput3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInput3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Sisi                            :");

        jTextFieldInput4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInput4.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldInput4.setText("Enter Value...");
        jTextFieldInput4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInput4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInput4FocusLost(evt);
            }
        });
        jTextFieldInput4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInput4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Sisi                            :");

        jTextFieldInput5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInput5.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldInput5.setText("Enter Value...");
        jTextFieldInput5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInput5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInput5FocusLost(evt);
            }
        });
        jTextFieldInput5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInput5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Sisi                            :");

        jTextFieldInput6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldInput6.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldInput6.setText("Enter Value...");
        jTextFieldInput6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldInput6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldInput6FocusLost(evt);
            }
        });
        jTextFieldInput6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInput6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(177, 177, 177)
                                                .addComponent(jLabelNewUsersTitle))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(45, 45, 45)
                                                                .addComponent(jButtonsSave)
                                                                .addGap(78, 78, 78)
                                                                .addComponent(jButtonReset)
                                                                .addGap(87, 87, 87)
                                                                .addComponent(jButtonClose)
                                                                .addGap(26, 26, 26))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldInput5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jTextFieldInput4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextFieldInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextFieldInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextFieldInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldInput6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(jLabelNewUsersTitle)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextFieldInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextFieldInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextFieldInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextFieldInput4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextFieldInput5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jTextFieldInput6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonReset)
                                        .addComponent(jButtonsSave)
                                        .addComponent(jButtonClose))
                                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>                        

    private void jTextFieldInput1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldInput1FocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(jTextFieldInput1.getText().equals("Enter Value..."))
        {
            jTextFieldInput1.setText("");
            jTextFieldInput1.setForeground(new Color(0,0,0));
        }
    }

    private void jTextFieldInput1FocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(jTextFieldInput1.getText().equals(""))
        {
            jTextFieldInput1.setText("Enter Value...");
            jTextFieldInput1.setForeground(new Color(153,153,153));
        }
    }

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
    }

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new Input6().setVisible(true);
    }

    private void jButtonsSaveActionPerformed(java.awt.event.ActionEvent evt) {




    }

    private void jTextFieldInput2FocusGained(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput2.getText().equals("Enter Value..."))
        {
            jTextFieldInput2.setText("");
            jTextFieldInput2.setForeground(new Color(0,0,0));
        }
    }

    private void jTextFieldInput2FocusLost(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput2.getText().equals(""))
        {
            jTextFieldInput2.setText("Enter Value...");
            jTextFieldInput2.setForeground(new Color(153,153,153));
        }
    }

    private void jTextFieldInput2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldInput3FocusGained(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput3.getText().equals("Enter Value..."))
        {
            jTextFieldInput3.setText("");
            jTextFieldInput3.setForeground(new Color(0,0,0));
        }
    }

    private void jTextFieldInput3FocusLost(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput3.getText().equals(""))
        {
            jTextFieldInput3.setText("Enter Value...");
            jTextFieldInput3.setForeground(new Color(153,153,153));
        }
    }

    private void jTextFieldInput3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldInput4FocusGained(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput4.getText().equals("Enter Value..."))
        {
            jTextFieldInput4.setText("");
            jTextFieldInput4.setForeground(new Color(0,0,0));
        }
    }

    private void jTextFieldInput4FocusLost(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput4.getText().equals(""))
        {
            jTextFieldInput4.setText("Enter Value...");
            jTextFieldInput4.setForeground(new Color(153,153,153));
        }
    }

    private void jTextFieldInput4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldInput5FocusGained(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput5.getText().equals("Enter Value..."))
        {
            jTextFieldInput5.setText("");
            jTextFieldInput5.setForeground(new Color(0,0,0));
        }
    }

    private void jTextFieldInput5FocusLost(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput5.getText().equals(""))
        {
            jTextFieldInput5.setText("Enter Value...");
            jTextFieldInput5.setForeground(new Color(153,153,153));
        }
    }

    private void jTextFieldInput5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldInput6FocusGained(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput6.getText().equals("Enter Value..."))
        {
            jTextFieldInput6.setText("");
            jTextFieldInput6.setForeground(new Color(0,0,0));
        }
    }

    private void jTextFieldInput6FocusLost(java.awt.event.FocusEvent evt) {
        if(jTextFieldInput6.getText().equals(""))
        {
            jTextFieldInput6.setText("Enter Value...");
            jTextFieldInput6.setForeground(new Color(153,153,153));
        }
    }

    private void jTextFieldInput6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonsSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNewUsersTitle;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldInput1;
    private javax.swing.JTextField jTextFieldInput2;
    private javax.swing.JTextField jTextFieldInput3;
    private javax.swing.JTextField jTextFieldInput4;
    private javax.swing.JTextField jTextFieldInput5;
    private javax.swing.JTextField jTextFieldInput6;
    // End of variables declaration                   
}